// 共享的 API 模型与领域类型统一放此目录。
// 按需新建文件（如 domain.ts）并在此 barrel 导出。
export * from "./ai-model";
export * from "./ai-chat";
export * from "./ai-system-prompt";
export * from "./api";
export * from "./api-path";
export * from "./code-table";
export * from "./dynamic-form";
export * from "./file";
export * from "./ganDaShi";
export * from "./mail";
export * from "./menu";
export * from "./menu-manager";
export * from "./org";
export * from "./process";
export * from "./role-manager";
export * from "./user";
export * from "./user-manager";
export * from "./website";
export * from "./website-manager";
